project:
  type: website

# COLORS:
# magenta: #c82f61
# gold: #ebab35 
# light pink: #f9eaf1 
# deep blue: #030bc8 or #2f3ec7 
# pantone blue: #325b74

website:
  title: "PGEforge"
  repo-url: https://github.com/mrc-ide/PGEforge
  repo-actions: [edit, issue]
  favicon: website_docs/img/PGEforge_hex.png
  
  back-to-top-navigation: true
  page-navigation: true
  
  page-footer:
    background: "#f9eaf1"
    foreground: "#c82f61"
    center: "This website is built with ❤️ and [Quarto](https://quarto.org/). &copy; 2023"
    
  sidebar:
    background: "#f9eaf1"
    logo: "website_docs/img/PGEforge_hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        text: "Source code"
        href: https://github.com/mrc-ide/PGEforge
    style: "docked"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: "Data"
        contents:
          - website_docs/data_description.qmd
          - text: "The data-DAG"
      - section: "Installing tools via R-universe"
      - section: "Tutorials"
        contents:
          - text: "**Overview of all tutorials**"
            file: tutorials_overview.qmd
          - section: "DRpower"
            contents:
            - text: "Summary"
              file: tutorials/DRpower/DRpower_background.Rmd
            - text: "Installation"
              file: tutorials/DRpower/DRpower_installation.Rmd
            - text: "Designing a study"
              file: tutorials/DRpower/DRpower_design.Rmd
            - text: "Analysis of *pfhrp2/3* data"
              file: tutorials/DRpower/DRpower_analysis_pfhrp2.Rmd
      - section: "Guiding principles for developing software"
        contents:
          - text: "Recommendations"
          - text: "How do I get my tool on PGEforge?"
      - section: "Events and meetings"
        contents:
            - text: "RADISH23 Hackathon"
              file: website_docs/radish23.qmd
      - href: website_docs/contributors.qmd
        text: "Contributors"

format:
  html:
    theme: [cosmo, website_docs/styles.scss] # note have to edit scss instead of just html so it works across whole website
    toc: true
    # fontcolor: "#c82f61"
    linkcolor: "#c82f61" 
    
execute:
  freeze: auto