project:
  type: website

# COLORS:
# magenta: #c82f61
# gold: #ebab35 
# light pink: #f9eaf1 
# deep blue: #030bc8 or #2f3ec7 
# pantone blue: #325b74

website:
  title: "PGEforge"
  repo-url: https://github.com/mrc-ide/PGEforge
  repo-actions: [edit, issue]
  favicon: website_docs/img/PGEforge_hex.png
  
  back-to-top-navigation: true
  page-navigation: true
  
  page-footer:
    background: "#f9eaf1"
    foreground: "#c82f61"
    center: "This website is built with ❤️ and [Quarto](https://quarto.org/). &copy; 2023"
    
  sidebar:
    background: "#f9eaf1"
    logo: "website_docs/img/PGEforge_hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        text: "Source code"
        href: https://github.com/mrc-ide/PGEforge
    style: "docked"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: "Data"
        contents:
          - website_docs/data_description.qmd
          - text: "The data-DAG (TODO)"
      - section: "Tool landscaping"
        contents:
          - text: "The landscaping matrix (TODO)"
          - text: "Installing via the plasmogenepi.r-universe (TODO)"
      - section: "Tutorials"
        contents:
          - text: "**Overview of all tutorials**"
            file: website_docs/tutorials_overview.qmd
          - section: "coiaf"
            contents:
            - text: "Summary"
              file: tutorials/coiaf/coiaf_background.Rmd
            - text: "Installation"
              file: tutorials/coiaf/coiaf_installation.Rmd
            - text: "Estimating COI from SNP data"
              file: tutorials/coiaf/coiaf_analysis.Rmd
          - section: "DEploidIBD"
            contents:
            - text: "Summary"
              file: tutorials/DEploidIBD/background.md
            - text: "Installation"
              file: tutorials/DEploidIBD/installation.md
            - text: "Part 1: Preparing your data"
              file: tutorials/DEploidIBD/part1-preparing-data.md
            - text: "Part 2: Running DEploidIBD"
              file: tutorials/DEploidIBD/part2-running-deploidibd.md
          - section: "DRpower"
            contents:
            - text: "Summary"
              file: tutorials/DRpower/DRpower_background.Rmd
            - text: "Installation"
              file: tutorials/DRpower/DRpower_installation.Rmd
            - text: "Designing a study"
              file: tutorials/DRpower/DRpower_design.Rmd
            - text: "Analysis of *pfhrp2/3* data"
              file: tutorials/DRpower/DRpower_analysis_pfhrp2.Rmd
          - section: "estMOI"
            contents:
            - text: "Summary"
              file: tutorials/estMOI/background.Rmd
            - text: "Installation"
              file: tutorials/estMOI/installation.Rmd
            - text: "Analyze data with `estMOI`"
              file: tutorials/estMOI/analysis.Rmd
          - section: "hmmIBD"
            contents:
            - text: "Summary"
              file: tutorials/hmmIBD/hmmIBD_background.Rmd
            - text: "Overview"
              file: tutorials/hmmIBD/hmmIBD_overview.md
            - text: "Installation"
              file: tutorials/hmmIBD/hmmIBD_installation.md
            - text: "Basic IBD analysis with `hmmIBD`"
              file: tutorials/hmmIBD/hmmIBD_analysis.md
          - section: "hmmibdr"
            contents:
            - text: "Summary"
              file: tutorials/hmmibdr/hmmibdr_background.Rmd
          - section: "MLMOI"
            contents:
            - text: "Summary"
              file: tutorials/MLMOI/Template_background.Rmd
          # - section: "moimix"
          #   contents:
          #   - text: "Summary"
          #     file: tutorials/moimix/moimix_background.Rmd
          #   - text: "Installation"
          #     file: tutorials/moimix/moimix_installation.Rmd
          #   - text: "Analyze data with `moimix`"
          #     file: tutorials/moimix/moimix_analysis.Rmd
          - section: "moire"
            contents:
            - text: "Summary"
              file: tutorials/moire/moire_background.Rmd
            - text: "Installation"
              file: tutorials/moire/moire_installation.Rmd
            - text: "Running moire example"
              file: tutorials/moire/moire_analysis.Rmd
          - section: "MultiLociBiallelicModel"
            contents:
            - text: "Summary"
              file: tutorials/MultiLociBiallelicModel/MultiLociBiallelicModel_background.qmd
            - text: "Installation"
              file: tutorials/MultiLociBiallelicModel/MultiLociBiallelicModel_installation.qmd
            - text: "Running `MultiLociBiallelicModel` on bialleic SNP data"
              file: tutorials/MultiLociBiallelicModel/MultiLociBiallelicModel_analysis.qmd
          - section: "paneljudge"
            contents:
            - text: "Summary"
              file: tutorials/paneljudge/paneljudge_background.Rmd
            - text: "Installation"
              file: tutorials/paneljudge/paneljudge_installation.Rmd
            - text: "Tutorial for Running `paneljudge`"
              file: tutorials/paneljudge/paneljudge_analysis.Rmd
          - section: "rehh"
            contents:
            - text: "Summary"
              file: tutorials/rehh/Template_background.Rmd
            - text: "Installation"
              file: tutorials/rehh/Template_installation.Rmd
            # - text: "Analyze data with `rehh`"
            #   file: tutorials/rehh/Template_analysis.Rmd
          - section: "THEREALMcCOIL"
            contents:
            - text: "Summary"
              file: tutorials/THEREALMcCOIL/RMCL_background.Rmd
            - text: "Installation"
              file: tutorials/THEREALMcCOIL/RMCL_installation.Rmd
            - text: "Analyze data with `rehh`"
              file: tutorials/THEREALMcCOIL/RMCL_analysis.Rmd
      - section: "Guiding principles"
        contents:
          - text: "Recommendations (TODO)"
          - text: "How do I get my tool on PGEforge? (TODO)"
      - section: "Events and meetings"
        contents:
            - text: "RADISH23 Hackathon"
              file: website_docs/radish23.qmd
      - href: website_docs/contributors.qmd
        text: "Contributors"

format:
  html:
    theme: [cosmo, website_docs/styles.scss] # note have to edit scss instead of just html so it works across whole website
    toc: true
    # fontcolor: "#c82f61"
    linkcolor: "#c82f61" 

execute:
  freeze: auto
  code-tools: true
  code-link: true
