project:
  type: website

# COLORS:
# magenta: #c82f61
# gold: #ebab35 
# light pink: #f9eaf1 
# deep blue: #030bc8 or #2f3ec7 
# pantone blue: #325b74

website:
  title: "PGEforge"
  repo-url: https://github.com/mrc-ide/PGEforge
  repo-actions: [edit, issue]
  favicon: website_docs/img/PGEforge_hex.png
  
  back-to-top-navigation: true
  page-navigation: true
  
  page-footer:
    background: "#f9eaf1"
    foreground: "#c82f61"
    center: "This website is built with 💖️, <i class='fab fa-r-project' style='color: #cf366c;'></i> and<img src='https://quarto.org/quarto.png' alt='Quarto' width='65px'/>. &copy; 2024"
    
  sidebar:
    background: "#f9eaf1"
    logo: "website_docs/img/PGEforge_hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        text: "Source code"
        href: https://github.com/mrc-ide/PGEforge
    style: "docked"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: website_docs/data_description.qmd
        contents:
          - text: "WGS"
            file: website_docs/data_wgs.qmd
          - text: "Microhaplotypes"
            file: website_docs/data_mhaps.qmd
          - text: "SNPs"
            file: website_docs/data_snps.qmd
          - text: "pfhrp2/3 deletion counts"
            file: website_docs/data_counts.qmd
      - section: "Tool landscaping"
        contents:
          - text: "The landscaping matrix"
            file: website_docs/tool_landscaping.qmd
          - text: "Installing via the plasmogenepi.r-universe"
            file: website_docs/R_universe.qmd
      - section: website_docs/software_standards.qmd
        contents:
          - text: "Overview by tool"
            file: website_docs/tools_to_standards.qmd
      - section: website_docs/tutorials_overview.qmd
        contents:
          - section: "coiaf"
            contents:
            - text: "Summary"
              file: tutorials/coiaf/coiaf_background.Rmd
            - text: "Installation"
              file: tutorials/coiaf/coiaf_installation.Rmd
            - text: "Estimating COI from SNP data"
              file: tutorials/coiaf/coiaf_analysis.Rmd
          - section: "DEploidIBD"
            contents:
            - text: "Summary"
              file: tutorials/DEploidIBD/background.md
            - text: "Installation"
              file: tutorials/DEploidIBD/installation.md
            - text: "Part 1: Preparing your data"
              file: tutorials/DEploidIBD/part1-preparing-data.md
            - text: "Part 2: Running DEploidIBD"
              file: tutorials/DEploidIBD/part2-running-deploidibd.md
          - section: "DRpower"
            contents:
            - text: "Summary"
              file: tutorials/DRpower/DRpower_background.Rmd
            - text: "Installation"
              file: tutorials/DRpower/DRpower_installation.Rmd
            - text: "Designing a study"
              file: tutorials/DRpower/DRpower_design.Rmd
            - text: "Analysis of *pfhrp2/3* data"
              file: tutorials/DRpower/DRpower_analysis_pfhrp2.Rmd
          - section: "dcifer"
            contents:
            - text: "Summary"
              file: tutorials/dcifer/dcifer_background.Rmd
            - text: "Installation"
              file: tutorials/dcifer/dcifer_installation.Rmd
            - text: "Tutorial"
              file: tutorials/dcifer/dcifer_analysis.Rmd
          - section: "estMOI"
            contents:
            - text: "Summary"
              file: tutorials/estMOI/background.Rmd
            - text: "Installation"
              file: tutorials/estMOI/installation.Rmd
            - text: "Analyze data with `estMOI`"
              file: tutorials/estMOI/analysis.Rmd
          - section: "hierfstat"
            contents:
            - text: "Summary"
              file: tutorials/hierfstat/background.Rmd
            - text: "Installation"
              file: tutorials/hierfstat/installation.Rmd
            - text: "Analyze data with `hierfstat`"
              file: tutorials/hierfstat/analysis.Rmd
          - section: "hmmIBD"
            contents:
            - text: "Summary"
              file: tutorials/hmmIBD/hmmIBD_background.Rmd
            - text: "Overview"
              file: tutorials/hmmIBD/hmmIBD_overview.md
            - text: "Installation"
              file: tutorials/hmmIBD/hmmIBD_installation.md
            - text: "Basic IBD analysis with `hmmIBD`"
              file: tutorials/hmmIBD/hmmIBD_analysis.md
          - section: "moire"
            contents:
            - text: "Summary"
              file: tutorials/moire/moire_background.Rmd
            - text: "Installation"
              file: tutorials/moire/moire_installation.Rmd
            - text: "Running moire example"
              file: tutorials/moire/moire_analysis.Rmd
          - section: "MultiLociBiallelicModel"
            contents:
            - text: "Summary"
              file: tutorials/MultiLociBiallelicModel/MultiLociBiallelicModel_background.qmd
            - text: "Installation"
              file: tutorials/MultiLociBiallelicModel/MultiLociBiallelicModel_installation.qmd
            - text: "Running `MultiLociBiallelicModel` on bialleic SNP data"
              file: tutorials/MultiLociBiallelicModel/MultiLociBiallelicModel_analysis.qmd
          - section: "paneljudge"
            contents:
            - text: "Summary"
              file: tutorials/paneljudge/paneljudge_background.Rmd
            - text: "Installation"
              file: tutorials/paneljudge/paneljudge_installation.Rmd
            - text: "Tutorial for Running `paneljudge`"
              file: tutorials/paneljudge/paneljudge_analysis.Rmd
          # - section: "rehh"
          #   contents:
          #   - text: "Summary"
          #     file: tutorials/rehh/Template_background.Rmd
          #   - text: "Installation"
          #     file: tutorials/rehh/Template_installation.Rmd
            # - text: "Analyze data with `rehh`"
            #   file: tutorials/rehh/Template_analysis.Rmd
          - section: "THEREALMcCOIL"
            contents:
            - text: "Summary"
              file: tutorials/THEREALMcCOIL/RMCL_background.Rmd
            - text: "Installation"
              file: tutorials/THEREALMcCOIL/RMCL_installation.Rmd
            - text: "Analyze data with `THEREALMcCOIL`"
              file: tutorials/THEREALMcCOIL/RMCL_analysis.Rmd
      - section: website_docs/workflows.qmd
        contents:
          - text: "Use cases"
          - text: "Coming soon!"
      - section: "How to contribute"
        contents:
          - website_docs/how_to_contribute.qmd
          - section: "Events and meetings"
            contents:
            - text: "RADISH23 Hackathon"
              file: website_docs/radish23.qmd
          - href: website_docs/contributors.qmd
            text: "Contributors"
          - href: website_docs/future_work.qmd
            text: "Future work"

format:
  html:
    theme: [cosmo, website_docs/styles.scss] # note have to edit scss instead of just html so it works across whole website
    toc: true
    # fontcolor: "#c82f61"
    linkcolor: "#c82f61" 
    header-includes: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet"/>

execute:
  freeze: auto
  code-tools: true
  code-link: true
