---
title: "isoRelate"
output: html_document
author: "Lyndan Henden"
date: "12 Dec 2023"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

<br/>
<br/>

## Summary sheet

```{r, echo=FALSE, warning=FALSE}
# read in summary sheet from file
df_summary <- read.csv("summary_sheet.csv", header = FALSE)

# produce formatted table
df_summary |>
  kbl(format = "html", col.names = NULL, table.attr = "style='width:50%;'", escape = FALSE) |>
  kable_styling(position = "left", bootstrap_options = c("striped", "hover", "condensed"))
```

## Purpose

A quick one paragraph description of what the tool does. For an example, see the [DRpower page](https://mrc-ide.github.io/PGEforge/tutorials/DRpower/DRpower_background.html).

## Existing resources

- Any existing online tutorials?
- Any important papers?

## Citation

BibTeX style citation. For an R package, you can get this using `citation(package = "name")`:

Here is an example for DRpower, using `citation(package = "DRpower")`:

```
@Manual{,
    title = {Identity-by-descent analyses for measuring population dynamics and selection in recombining pathogens},
    author = {Lyndan Henden, Stuart Lee, Alyssa Barry, Melanie Bahlo},
    note = {R package version 1.0.2},
  }
```
