---
title: "Tool resources"
subtitle: "Comprehensive guides covering the entire process of using *Plasmodium* genomic analysis tools"
format: html
---

## Overview
The aim of the PGEforge resources is to provide worked examples that show *how* to use a tool by *working through* code. This involves code showing you how to install the tool, what input data formats you need to use, how to wrangle the data (if applicable), and how to use the tool functionalities to analyse data. Summary documents detailing the purpose of each tool can also help you decide which tool you may want to use for a certain application.

The following resources are available for each tool:

- A summary document detailing the main purpose and use cases, license, code repository, relevant publication(s), citation information and links to any additional resources
- Complete installation instructions
- A fully reproducible and worked-through tutorial showing example usage of the tool and its functionalities. This often uses the [canonical simulated or empirical datasets](data_description.qmd) as input data
- (*Coming soon*) For some tools, we have undertaken systematic benchmarking on simulated data to evaluate performance and accuracy 

## How to contribute

This is a live resource and we plan to continue adding to this as new tools become available! We hope this will grow into a common resource for analysis of malaria genetic data. 

If you are interested in contributing, there are [templates available](https://mrc-ide.github.io/PGEforge/tutorials/Template/Template_background.html) and [instructions](how_to_contribute.qmd) on how to get started. 