on:
  push:
    branches:
      - develop
      - main
      - feature/website
  pull_request:
    branches:
      - develop
      - main

name: check-quarto-render

jobs:
  check-quarto-render:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up quarto
      uses: quarto-dev/quarto-actions/setup@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        R -e 'install.packages("quarto", repos="http://cran.rstudio.com/")'

    - name: Render quarto website
      run: |
        R -e 'library(quarto); quarto::quarto_render()'

    - name: Upload check results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: quarto-render-output
        path: _site