on:
  push:
    branches:
      - develop
      - main
      - feature/website
  pull_request:
    branches:
      - develop
      - main

name: check-quarto-render

jobs:
  check-quarto-render:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render quarto website
      uses: quarto-dev/quarto-actions/render@v2
      with:
        path: _site