on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: publish-quarto-website

permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up quarto
      uses: quarto-dev/quarto-actions/setup@v2
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Pages (and render)
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}